@echo off
set glslcPATH= glslc.exe

echo Kompilacja shader.vert do vert.spv ...
%glslcPath% shader.vert -o ..\vert.spv
echo Kompilacja shader.frag do frag.spv ...
%glslcPath% shader.frag -o ..\frag.spv

echo Kompilacja shader2.vert do vert2.spv ...
%glslcPath% shader2.vert -o ..\vert2.spv
echo Kompilacja shader2.frag do frag2.spv ...
%glslcPath% shader2.frag -o ..\frag2.spv

echo Kompilacja pointLight.vert do pointLight.vert.spv ...
%glslcPath% pointLight.vert -o ..\pointLight.vert.spv
echo Kompilacja pointLight.frag do pointLight.frag.spv ...
%glslcPath% pointLight.frag -o ..\pointLight.frag.spv

echo Kompilacja sphere.vert do vertSphere.spv ...
%glslcPath% sphere.vert -o ..\vertSphere.spv
echo Kompilacja sphere.frag do fragSphere.spv ...
%glslcPath% sphere.frag -o ..\fragSphere.spv

echo Kompilacja monkey.vert do vertMonkey.spv ...
%glslcPath% monkey.vert -o ..\vertMonkey.spv
echo Kompilacja monkey.frag do fragMonkey.spv ...
%glslcPath% monkey.frag -o ..\fragMonkey.spv

echo Kompilacja colors.vert do vertColors.spv ...
%glslcPath% colors.vert -o ..\vertColors.spv
echo Kompilacja colors.frag do fragColors.spv ...
%glslcPath% colors.frag -o ..\fragColors.spv


